FROM node:current-buster-slim

WORKDIR /relationship-bot

COPY . .

RUN apt update

RUN apt install graphviz -y

RUN apt install python3 -y

RUN apt install make -y

RUN apt install gcc -y

RUN npm install

RUN npm install -g pm2

CMD ["pm2-runtime", "index.js"]