FROM node:current-buster-slim

WORKDIR /relationship-bot

COPY . .

RUN npm install

RUN npm install -g pm2

RUN apt update

RUN apt install graphviz -y

RUN apt install python3 -y

CMD ["pm2-runtime", "index.js"]